# Generated by Django 5.0.3 on 2024-03-08 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Django', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personas',
            name='time',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='personas',
            name='update',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='personas',
            name='date',
            field=models.DateField(default=None, null=True),
        ),
    ]
